export { default } from 'react-router';
export {
  __esModule,
  Router,
  Link,
  IndexLink,
  withRouter,
  IndexRedirect,
  IndexRoute,
  Redirect,
  Route,
  History,
  Lifecycle,
  RouteContext,
  useRoutes,
  createRoutes,
  RouterContext,
  RoutingContext,
  PropTypes,
  locationShape,
  routerShape,
  match,
  useRouterHistory,
  formatPattern,
  applyRouterMiddleware,
  browserHistory,
  hashHistory,
  createMemoryHistory,
} from 'react-router';
